#############################################################################
# Makefile for building: M5LibTest.app/Contents/MacOS/M5LibTest
# Generated by qmake (3.0) (Qt 5.6.1)
# Project:  M5LibTest.pro
# Template: app
# Command: /Users/chenchaowei/Qt5.6.1/5.6/clang_64/bin/qmake -spec macx-clang CONFIG+=x86_64 -o Makefile M5LibTest.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_TESTLIB_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR='"/Users/chenchaowei/work/qt_project/eye/M5LibTestBK"'
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -IM5Lib/include -IM5Lib/include -I../../../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers -I../../../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers -I../../../../Qt5.6.1/5.6/clang_64/lib/QtNetwork.framework/Headers -I../../../../Qt5.6.1/5.6/clang_64/lib/QtSql.framework/Headers -I../../../../Qt5.6.1/5.6/clang_64/lib/QtTest.framework/Headers -I../../../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers -Iobj -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -Iobj/ui_header -I../../../../Qt5.6.1/5.6/clang_64/mkspecs/macx-clang -F/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib
QMAKE         = /Users/chenchaowei/Qt5.6.1/5.6/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = M5LibTest1.0.0
DISTDIR = /Users/chenchaowei/work/qt_project/eye/M5LibTestBK/obj/M5LibTest1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -weak_framework XCTest -Wl,-rpath,/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib -L/Users/chenchaowei/work/qt_project/eye/M5LibTestBK/M5Lib/ -lM5Lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtNetwork -framework QtSql -framework QtTest -framework Security -framework ApplicationServices -framework Foundation -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = main.cpp \
		widget.cpp obj/moc_M5Library.cpp \
		obj/moc_Network.cpp \
		obj/moc_DataBase.cpp \
		obj/moc_widget.cpp
OBJECTS       = obj/main.o \
		obj/widget.o \
		obj/moc_M5Library.o \
		obj/moc_Network.o \
		obj/moc_DataBase.o \
		obj/moc_widget.o
DIST          = ../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/qdevice.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/common/unix.conf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/common/mac.conf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/common/macx.conf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/common/clang.conf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/qconfig.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/mac/default_pre.prf \
		M5Lib/include/M5Lib.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/qt.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/resources.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/moc.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/xctest.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/testlib_defines.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/uic.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/file_copies.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/lex.prf \
		M5LibTest.pro M5Lib/include/M5Library.h \
		M5Lib/include/Network.h \
		M5Lib/include/DataBase.h \
		widget.h main.cpp \
		widget.cpp
QMAKE_TARGET  = M5LibTest
DESTDIR       = 
TARGET        = M5LibTest.app/Contents/MacOS/M5LibTest


first: all
####### Build rules

$(TARGET): /Users/chenchaowei/work/qt_project/eye/M5LibTestBK/M5Lib/libM5Lib.a obj/ui_header/ui_widget.h $(OBJECTS)  
	@test -d M5LibTest.app/Contents/MacOS/ || mkdir -p M5LibTest.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: M5LibTest.pro ../../../../Qt5.6.1/5.6/clang_64/mkspecs/macx-clang/qmake.conf ../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/qdevice.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/common/unix.conf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/common/mac.conf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/common/macx.conf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/common/clang.conf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/qconfig.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/mac/default_pre.prf \
		M5Lib/include/M5Lib.pri \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/qt.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/resources.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/moc.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/xctest.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/testlib_defines.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/uic.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/file_copies.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/lex.prf \
		M5LibTest.pro \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtSql.framework/QtSql.prl \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtTest.framework/QtTest.prl \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile M5LibTest.pro
../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/spec_pre.prf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/qdevice.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/device_config.prf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/common/unix.conf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/common/mac.conf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/common/macx.conf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/common/sanitize.conf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/common/gcc-base.conf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/common/clang.conf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/common/clang-mac.conf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/qconfig.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/qt_functions.prf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/qt_config.prf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/macx-clang/qmake.conf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/default_pre.prf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/mac/default_pre.prf:
M5Lib/include/M5Lib.pri:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/resolve_config.prf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/default_post.prf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/mac/sdk.prf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/mac/default_post.prf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/warn_on.prf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/qt.prf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/resources.prf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/moc.prf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/xctest.prf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/testlib_defines.prf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/unix/opengl.prf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/uic.prf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/unix/thread.prf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/file_copies.prf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/mac/rez.prf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/testcase_targets.prf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/exceptions.prf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/yacc.prf:
../../../../Qt5.6.1/5.6/clang_64/mkspecs/features/lex.prf:
M5LibTest.pro:
../../../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/QtGui.prl:
../../../../Qt5.6.1/5.6/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
../../../../Qt5.6.1/5.6/clang_64/lib/QtSql.framework/QtSql.prl:
../../../../Qt5.6.1/5.6/clang_64/lib/QtTest.framework/QtTest.prl:
../../../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile M5LibTest.pro

qmake_all: FORCE

M5LibTest.app/Contents/PkgInfo: 
	@test -d M5LibTest.app/Contents || mkdir -p M5LibTest.app/Contents
	@$(DEL_FILE) M5LibTest.app/Contents/PkgInfo
	@echo "APPL????" > M5LibTest.app/Contents/PkgInfo
M5LibTest.app/Contents/Resources/empty.lproj: 
	@test -d M5LibTest.app/Contents/Resources || mkdir -p M5LibTest.app/Contents/Resources
	@touch M5LibTest.app/Contents/Resources/empty.lproj
	
M5LibTest.app/Contents/Info.plist: 
	@test -d M5LibTest.app/Contents || mkdir -p M5LibTest.app/Contents
	@$(DEL_FILE) M5LibTest.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,RogerProject.M5LibTest,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,M5LibTest,g" -e "s,@LIBRARY@,M5LibTest,g" -e "s,@TYPEINFO@,????,g" ../../../../Qt5.6.1/5.6/clang_64/mkspecs/macx-clang/Info.plist.app >M5LibTest.app/Contents/Info.plist

all: Makefile \
		M5LibTest.app/Contents/PkgInfo \
		M5LibTest.app/Contents/Resources/empty.lproj \
		M5LibTest.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents M5Lib/include/M5Library.h M5Lib/include/Network.h M5Lib/include/DataBase.h widget.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp widget.cpp $(DISTDIR)/
	$(COPY_FILE) --parents widget.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r M5LibTest.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: obj/moc_M5Library.cpp obj/moc_Network.cpp obj/moc_DataBase.cpp obj/moc_widget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) obj/moc_M5Library.cpp obj/moc_Network.cpp obj/moc_DataBase.cpp obj/moc_widget.cpp
obj/moc_M5Library.cpp: ../../../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtSql.framework/Headers/QSqlDatabase \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QVariantList \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		M5Lib/include/Network.h \
		M5Lib/include/DataBase.h \
		M5Lib/include/M5Library.h
	/Users/chenchaowei/Qt5.6.1/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/mkspecs/macx-clang -I/Users/chenchaowei/work/qt_project/eye/M5LibTestBK -I/Users/chenchaowei/work/qt_project/eye/M5LibTestBK/M5Lib/include -I/Users/chenchaowei/work/qt_project/eye/M5LibTestBK/M5Lib/include -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtNetwork.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtSql.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtTest.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -F/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib M5Lib/include/M5Library.h -o obj/moc_M5Library.cpp

obj/moc_Network.cpp: ../../../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		M5Lib/include/Network.h
	/Users/chenchaowei/Qt5.6.1/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/mkspecs/macx-clang -I/Users/chenchaowei/work/qt_project/eye/M5LibTestBK -I/Users/chenchaowei/work/qt_project/eye/M5LibTestBK/M5Lib/include -I/Users/chenchaowei/work/qt_project/eye/M5LibTestBK/M5Lib/include -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtNetwork.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtSql.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtTest.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -F/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib M5Lib/include/Network.h -o obj/moc_Network.cpp

obj/moc_DataBase.cpp: ../../../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtSql.framework/Headers/QSqlDatabase \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		M5Lib/include/DataBase.h
	/Users/chenchaowei/Qt5.6.1/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/mkspecs/macx-clang -I/Users/chenchaowei/work/qt_project/eye/M5LibTestBK -I/Users/chenchaowei/work/qt_project/eye/M5LibTestBK/M5Lib/include -I/Users/chenchaowei/work/qt_project/eye/M5LibTestBK/M5Lib/include -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtNetwork.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtSql.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtTest.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -F/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib M5Lib/include/DataBase.h -o obj/moc_DataBase.cpp

obj/moc_widget.cpp: ../../../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		widget.h
	/Users/chenchaowei/Qt5.6.1/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/mkspecs/macx-clang -I/Users/chenchaowei/work/qt_project/eye/M5LibTestBK -I/Users/chenchaowei/work/qt_project/eye/M5LibTestBK/M5Lib/include -I/Users/chenchaowei/work/qt_project/eye/M5LibTestBK/M5Lib/include -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtNetwork.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtSql.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtTest.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -F/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib widget.h -o obj/moc_widget.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: obj/ui_header/ui_widget.h
compiler_uic_clean:
	-$(DEL_FILE) obj/ui_header/ui_widget.h
obj/ui_header/ui_widget.h: widget.ui
	/Users/chenchaowei/Qt5.6.1/5.6/clang_64/bin/uic widget.ui -o obj/ui_header/ui_widget.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

obj/main.o: main.cpp widget.h \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o main.cpp

obj/widget.o: widget.cpp widget.h \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		obj/ui_header/ui_widget.h \
		M5Lib/include/M5Library.h \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtSql.framework/Headers/QSqlDatabase \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QVariantList \
		../../../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		M5Lib/include/Network.h \
		M5Lib/include/DataBase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/widget.o widget.cpp

obj/moc_M5Library.o: obj/moc_M5Library.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_M5Library.o obj/moc_M5Library.cpp

obj/moc_Network.o: obj/moc_Network.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_Network.o obj/moc_Network.cpp

obj/moc_DataBase.o: obj/moc_DataBase.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_DataBase.o obj/moc_DataBase.cpp

obj/moc_widget.o: obj/moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_widget.o obj/moc_widget.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

